# https://www.youtube.com/watch?v=M2Wit3w2wLU&list=PLmOn9nNkQxJGVG1ktTV4SedFWuyef_Pi0&index=21
server:
  port: 80

spring:
  application:
    name: cloud-order-service

# https://youtu.be/ARfdin7xoZI?t=340
eureka:
  client:
    # whether register current service to eureka
    register-with-eureka: true
    # whether let eureka server get current registry info. Have to set as true if in cluster mode, so can run with ribbon for load balance
    fetchRegistry: true
    service-url:
      # single node mode
      #defaultZone: http://localhost:7001/eureka
      # cluster mode
      defaultZone:  http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
