# https://www.youtube.com/watch?v=M2Wit3w2wLU&list=PLmOn9nNkQxJGVG1ktTV4SedFWuyef_Pi0&index=21
server:
  port: 80

spring:
  application:
    name: cloud-order-feign-service

# https://youtu.be/ARfdin7xoZI?t=340
eureka:
  client:
    # a pure client, so NO need to register on eureka
    register-with-eureka: false
    service-url:
      # single node mode
      #defaultZone: http://localhost:7001/eureka
      # cluster mode
      defaultZone:  http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
