spring:
  application:
    name: user-system
  datasource:
    url: jdbc:mysql://localhost:3306/user_system
    username: root
    password:
    #ype: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    separator: //
  redis:
    host: 127.0.0.1
    port: 6379
    password:
#    sever:
#      port:
#        8888
