# book p.3-67
# https://github.com/yennanliu/SpringPlayground/blob/main/courses/springBoot_springCloud_%E9%A0%82%E7%B4%9A%E9%96%8B%E7%99%BC_src_code/chapter03-gateway/src/main/resources/application.yml
spring:
  cloud:
    gateway:
      # service discovery
      discovery:
        locator:
          enabled: true
      # routing
      routes:
        - id: sso-resourceserver
          uri: lb://sso-resourceserver
          predicates:
            - path=/resources/**
          filters:
            - StripPrefix=1