# book p.3-67
# https://github.com/yennanliu/SpringPlayground/blob/main/courses/springBoot_springCloud_%E9%A0%82%E7%B4%9A%E9%96%8B%E7%99%BC_src_code/chapter03-gateway/src/main/resources/application.yml
spring:
  cloud:
    gateway:
      #开启网关服务注册发现机制
      discovery:
        locator:
          enabled: true
      #路由配置（网关基本构建模版，由id、目标uri、一组predicates及一组filters构成）
      routes:
        - id: sso-resourceserver
          #lb代表从注册中心获取服务，格式为lb://$(注册服务的名字)
          uri: lb://sso-resourceserver
          predicates:
            #通过路径进行匹配
            - Path=/resources/**
          filters:
            - StripPrefix=1