spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sso
    username: root
    password:
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    separator: //