# https://youtu.be/wIR4X0mYSa0?t=219
# https://youtu.be/wIR4X0mYSa0?t=556
# https://github.com/yennanliu/SpringPlayground/blob/main/courses/%E8%B0%B7%E7%B2%92%E5%95%86%E5%9F%8E_%E5%85%A8%E6%A3%A7%E9%96%8B%E7%99%BC_src_code/docs/%E4%BB%A3%E7%A0%81/gulimall/gulimall-member/src/main/resources/application.yml

spring:
  # https://youtu.be/wk1r_ERKLJY?t=215
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # gateway mapping setting
    # https://youtu.be/F8WyHeaEf9E?t=489
    # https://cloud.spring.io/spring-cloud-gateway/reference/html/
    gateway:
      routes:
#        - id: test_route1
#          uri: https://google.com
#          predicates:
#            - Query=url,goog
#        - id: test_route2
#          uri: https://www.mozilla.org/en-US/firefox/new/
#          predicates:
#            - Query=url,fox,fire
        # NOTE: we put "specific" rule before general, so this one can be executed first
        # https://youtu.be/KKFJPtW3730?t=79
        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters: # overwrite request path : https://cloud.spring.io/spring-cloud-gateway/reference/html/#global-filters
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters: # overwrite request path : https://cloud.spring.io/spring-cloud-gateway/reference/html/#global-filters
            - RewritePath=/api/thirdparty/(?<segment>/?.*), /$\{segment}

        - id: member_route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters: # overwrite request path : https://cloud.spring.io/spring-cloud-gateway/reference/html/#global-filters
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        # https://youtu.be/Wcnwj5eLMiY?t=202
        - id: ware_route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters: # overwrite request path : https://cloud.spring.io/spring-cloud-gateway/reference/html/#global-filters
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        # https://youtu.be/QngyGaQXxz4?t=981
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**  # for any FE request, use "api" prefix
          filters: # overwrite request path : https://cloud.spring.io/spring-cloud-gateway/reference/html/#global-filters
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}
  application:
    name: gulimall-gateway

server:
  port: 88 # set gateway port as 88