# https://www.youtube.com/watch?v=3yGY9RxCtOc&list=PLmOn9nNkQxJGVG1ktTV4SedFWuyef_Pi0&index=17
# https://www.youtube.com/watch?v=ukm7jep5doc&list=PLmOn9nNkQxJGVG1ktTV4SedFWuyef_Pi0&index=20
server:
  port: 7002
eureka:
  instance:
    #hostname: localhost
    hostname: eureka7002.com  # eureka service instance name
  client:
    # no need to register itself
    register-with-eureka: false
    fetch-registry: false
    service-url:
      # url for service register/access (via eureka)
      # https://blog.csdn.net/xiaozhu0301/article/details/109604443
      # single node mode
      #defaultZone: http://${eureka.instance.hostname}${server.port}/eureka/
      # cluster mode
      defaultZone: http://eureka7001.com:7001/eureka/