Spring:
  mvc:
    #    static-path-pattern: /res/**   # change default url path for static resources
    #  resources:                       # change default file directory for static resources
    #    static-locations: [classpath:/my_resources]
    #    add-mappings: false            # note !! if "false", will block ALL static resources mapping
    cache:
      period : 1                # set up cache period, unit : second
    hiddenmethod:
      filter:
        enabled: true            # enable form (表單) REST function
    contentnegotiation:          # enable content negotiation. e.g. : http://localhost:8888/person?format=json, http://localhost:8888/person?format=xml
      favor-parameter: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#server:
#  servlet:
#    context-path: /world         # will make default URL path from http://localhost:8888 to http://localhost:8888/world/