server:                  #配置server
  tomcat:       #springboot乱码解决
    uri-encoding: UTF-8
  port: 8181

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true  #开启restful支持，默认只支持post个get
  http:       #springboot乱码解决
    encoding:
      force: true
      charset: utf-8
      enabled: true

eureka:
  instance:
    #单机 hostname: localhost
    hostname: eureka8181.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka8182.com:8182/eureka/,http://eureka8183.com:8183/eureka/

logging:
  config: classpath:log/log4j2.xml
