server:                  #配置server
  tomcat:       #springboot乱码解决
    uri-encoding: UTF-8
  port: 8096

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true  #开启restful支持，默认只支持post个get
  http:       #springboot乱码解决
    encoding:
      force: true
      charset: utf-8
      enabled: true
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-operation-route
          uri: lb://user-operation
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
        - id: main-operation-route
          uri: lb://school-operation
          predicates:
            - Path=/courseType/**
          filters:
            - RewritePath=/courseType/(?<path>.*), /$\{path}
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://localhost:9411/ # 指定了 Zipkin 服务器的地址

eureka:
  client: #客户端注册进eureka服务列表内
    serviceUrl:
      defaultZone: http://eureka8181.com:8181/eureka/,http://eureka8182.com:8182/eureka/,http://eureka8183.com:8183/eureka/
  instance:
    instanceId: ${spring.cloud.client.ip-address}:${server.port}:gateway-server
    preferIpAddress: true     #访问路径可以显示IP地址

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 50000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000