Spring:
  mvc:
    #    static-path-pattern: /res/**   # change default url path for static resources
    #  resources:                       # change default file directory for static resources
    #    static-locations: [classpath:/my_resources]
    #    add-mappings: false            # note !! if "false", will block ALL static resources mapping
    cache:
      period : 1                # set up cache period, unit : second
    hiddenmethod:
      filter:
        enabled: true            # enable form (表單) REST function
    contentnegotiation:          # enable content negotiation. e.g. : http://localhost:8888/person?format=json, http://localhost:8888/person?format=xml
      favor-parameter: true
  # mysql : https://www.youtube.com/watch?v=1uG7UXdiCYM&list=PLmOn9nNkQxJFKh2PMfWbGT7RVuMowsx-u&index=61
  datasource:
    url: jdbc:mysql://localhost:3306/sales
    username: root
    #password:
    driver-class-name: com.mysql.cj.jdbc.Driver  #com.mysql.jdbc.Driver
  jdbc:
    template:
      query-timeout: 3 # timeout if 3 sec no result

#server:
#  servlet:
#    context-path: /world         # will make default URL path from http://localhost:8888 to http://localhost:8888/world/