# https://github.com/yennanliu/SpringPlayground/blob/main/courses/springBoot_springCloud_%E9%A0%82%E7%B4%9A%E9%96%8B%E7%99%BC_src_code/chapter05-wallet/src/main/resources/application-test.yml
#数据库宿主机地址
spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/wallet
    username: root
    password: 123456

  #注册中心地址
  cloud:
    consul:
      host: host.docker.internal
      #host: localhost
      port: 8500