version: '3'
services:
  app:
    restart: always
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/db_name
      - SPRING_DATASOURCE_USERNAME=db_user
      - SPRING_DATASOURCE_PASSWORD=db_password
    depends_on:
      - mysql
    command: mvn clean spring-boot:run

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
