#spring:
#  application:
#    name: warehouse-system
#  datasource:
#    url: jdbc:mysql://localhost:3306/warehouse_system
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  thymeleaf:
#    encoding: UTF-8
#    cache: false
#    mode: LEGACYHTML5
#mybatis-plus:
#  global-config:
#    banner: true
#  configuration:
#    cache-enabled: false