version: '3'
services:
  app:
    restart: always
    build: ./backend/EmployeeSystem
    working_dir: /app
    volumes:
      - ./backend/EmployeeSystem:/app
    ports:
      - "9998:9998"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/employee_system
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create  # Set the Hibernate ddl-auto property here
      - SPRING_JPA_GENERATE_DDL=true
    depends_on:
      - mysql
    command: mvn clean spring-boot:run -DskipTests

  vue:
    restart: always
    build: ./frontend/employee-system-ui
    working_dir: /app
    ports:
      - "8080:8080"  # Map host port 8080 to container port 8080
    volumes:
      - ./frontend/employee-system-ui:/app  # Mount the current directory into the container
    command: npm run serve

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      #https://stackoverflow.com/questions/66831863/mysql-docker-container-keeps-restarting
      #MYSQL_USER: root # NO NEED to create root user, since it is created automatically
      MYSQL_DATABASE: employee_system
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
