spring:
  # book p.3-41
  datasource:
    url: jdbc:mysql://localhost:3306/resource_server
    username: root
    password:
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    separator: //
mybatis:
  #mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
# book p.3-46
security:
  oauth2:
    authorization: http://localhost:9092/oauth/check_token
    clientId: resourceClient
    clientSecret: 123456 # TODO: check this