version: '3'
services:
  app1:
    restart: always
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2/repository:/root/.m2/repository  # Mount Maven local repository
    ports:
      - "9999:9999"
    #    expose:
    #      - "9999"
    platform: linux/amd64
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/spring_bank
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create  # Set the Hibernate ddl-auto property here
      - SPRING_JPA_GENERATE_DDL=true
      - SERVER_PORT=9999
      - SPRING_REDIS_HOST=redis  # Set Redis host
      - SPRING_REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mysql
      - redis
    command: mvn clean spring-boot:run -DskipTests

  app2:
    restart: always
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2/repository:/root/.m2/repository  # Mount Maven local repository
    ports:
      - "9998:9998"
    #    expose:
    #      - "9998"
    platform: linux/amd64
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/spring_bank
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create  # Set the Hibernate ddl-auto property here
      - SPRING_JPA_GENERATE_DDL=true
      - SERVER_PORT=9998
      - SPRING_REDIS_HOST=redis  # Set Redis host
      - SPRING_REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mysql
      - redis
    command: mvn clean spring-boot:run -DskipTests

  nginx:
    image: nginx
    restart: always
    ports:
      #- "8080:80"
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/index.html:/app/html:ro
    depends_on:
      - app1
      - app2

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: spring_bank
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    platform: linux/amd64
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:latest
    restart: always
    platform: linux/amd64
    ports:
      - "6379:6379"  # Expose Redis port

volumes:
  mysql-data:
