# https://github.com/yennanliu/SpringPlayground/blob/main/courses/springBoot_springCloud_%E9%A0%82%E7%B4%9A%E9%96%8B%E7%99%BC_src_code/chapter05-wallet/src/main/docker/docker-compose.yml
version: '3.2'
services:
  wallet:
    image: wallet:1.0-SNAPSHOT
    hostname: wallet
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-debug}
    ports:
      - "9090:9090"
    networks:
      - mynet
networks:
  mynet:
    external: true