server:
  port: 8004

spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource  # current data src type
#    driver-class-name: org.gjt.mm.mysql.Driver    # mysql driver
#    url: jdbc:mysql://localhost:3306/data?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: