server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    # do not register self
    register-with-eureka: false
    # declare as register
    fetch-registry: false
    # url to qurey to lookup service
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka