spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:54321/gis
    username: gis
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    separator: //

#MyBatis-Plus集成配置
mybatis-plus:
  # 需要额外定义的Mybatis XML文件放在resource目录classpath:mybatis/*.xml
  mapper-locations: classpath:mybatis/*.xml
  # PO实体类扫描包路径，多个package用逗号分割
  typeAliasesPackage: com.wudimanong.efence.dao.model
  #Mybatis-Plus处理PostGis类型映射问题
  typeHandlersPackage: com.eyougo.mybatis.postgis.type
  global-config:
    db-config:
      #主键类型
      id-type: auto
      #字段策略
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: postgresql
    refresh: false
  configuration:
    #开启此配置会自动将下划线格式的表字段，转换为以驼峰命名的属性
    map-underscore-to-camel-case: true
    cache-enabled: false
    #日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl