spring:
  application:
    name: user-system
  datasource:
    url: jdbc:mysql://localhost:3306/sso
    username: root
    password:
    #ype: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    separator: //