server:
  port: 80

spring:
  application:
    name: cloud-order-service

# https://youtu.be/ARfdin7xoZI?t=340
eureka:
  client:
    # whether register current service to eureka
    register-with-eureka: true
    # whether let eureka server get current registry info. Have to set as true if in cluster mode, so can run with ribbon for load balance
    fetchRegistry: true
    service-url:
      # https://blog.csdn.net/xiaozhu0301/article/details/109604443
      defaultZone: http://localhost:7001/eureka