Spring:
  mvc:
    cache:
      period : 1                # set up cache period, unit : second
    hiddenmethod:
      filter:
        enabled: true            # enable form (表單) REST function
    contentnegotiation:          # enable content negotiation. e.g. : http://localhost:8888/person?format=json, http://localhost:8888/person?format=xml
      favor-parameter: true
  # mysql : https://www.youtube.com/watch?v=1uG7UXdiCYM&list=PLmOn9nNkQxJFKh2PMfWbGT7RVuMowsx-u&index=61
  datasource:
    url: jdbc:mysql://localhost:3306/data #jdbc:mysql://localhost:3306/sales
    username: root
    #password:
    driver-class-name: com.mysql.cj.jdbc.Driver  #com.mysql.jdbc.Driver
    # for druid-spring-boot-starter
  jdbc:
    template:
      query-timeout: 3 # timeout if no result in 3 sec
