Spring:
  mvc:
    cache:
      period : 1                # set up cache period, unit : second
    hiddenmethod:
      filter:
        enabled: true            # enable form (表單) REST function
    contentnegotiation:          # enable content negotiation. e.g. : http://localhost:8888/person?format=json, http://localhost:8888/person?format=xml
      favor-parameter: true
    # for druid-spring-boot-starter
  jdbc:
    template:
      query-timeout: 3 # timeout if no result in 3 sec
