version: '3'
services:
  app1:
    restart: always
    build: ./backend/DataPlatform/FlinkRestService # backend dockerfile
    working_dir: /app
    volumes:
      - ./backend/DataPlatform:/app
      - ~/.m2/repository:/root/.m2/repository  # Mount Maven local repository
    ports:
      - "9999:9999"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/data_platform
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create  # Set the Hibernate ddl-auto property here
      - SPRING_JPA_GENERATE_DDL=true
      - SERVER_PORT=9999
      #- flink.base_url=http://jobmanager:8083
    depends_on:
      - mysql
    command: mvn clean spring-boot:run -DskipTests

  app2:
    restart: always
    build: ./backend/DataPlatform/FlinkRestService # backend dockerfile
    working_dir: /app
    volumes:
      - ./backend/DataPlatform:/app
      - ~/.m2/repository:/root/.m2/repository  # Mount Maven local repository
    ports:
      - "9998:9998"  # Port mapping for app2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/data_platform
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create  # Set the Hibernate ddl-auto property here
      - SPRING_JPA_GENERATE_DDL=true
      - SERVER_PORT=9998
      #- flink.base_url=http://jobmanager:8083
    depends_on:
      - mysql
    command: mvn clean spring-boot:run -DskipTests

  vue:
    restart: always
    build: ./frontend/data-platform-ui
    working_dir: /app
    ports:
      - "8080:8080"  # Map host port 8080 to container port 8080
    volumes:
      - ./frontend/data-platform-ui:/app  # Mount the current directory into the container
    command: npm run serve

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: data_platform
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/index.html:/app/html:ro
    depends_on:
      - app1
      - app2

  # jobmanager:
  #   image: flink:1.17-scala_2.12-java11
  #   ports:
  #     - "8083:8081"
  #   command: jobmanager
  #   environment:
  #     - |
  #       FLINK_PROPERTIES=
  #       jobmanager.rpc.address: jobmanager

  # taskmanager:
  #   image: flink:1.17-scala_2.12-java11
  #   depends_on:
  #     - jobmanager
  #   command: taskmanager
  #   scale: 1
  #   environment:
  #     - |
  #       FLINK_PROPERTIES=
  #       jobmanager.rpc.address: jobmanager
  #       taskmanager.numberOfTaskSlots: 2

volumes:
  mysql-data: