Spring:
  # https://blog.csdn.net/qq_41604890/article/details/114553632
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true # enable form (表單) REST function
