Spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true # enable form (表單) REST function
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: 678951533842-l987a5fs2p3pnpdkkf1sin07gjqnovrq.apps.googleusercontent.com
#            clientSecret:
#            scope:
#              - email
#              - profile