spring:
  application:
    name: course-system
  datasource:
    url: jdbc:mysql://localhost:3306/course_system
    username: root
    password:
    #ype: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: LEGACYHTML5


mybatis-plus:
  mapper-locations: classpath:mybatis/*Mapper.xml
  global-config:
    banner: true
  configuration:
    cache-enabled: false

#logging:
#  config: classpath:log4j2/log4j2.xml