spring:
  application:
    name: course-system
  datasource:
    url: jdbc:mysql://localhost:3306/course_system
    username: root
    password:
    #ype: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
