---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: __APP_NAME__
spec:
  replicas: __REPLICAS__
  selector:
    matchLabels:
      app: __APP_NAME__
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: __APP_NAME__
    spec:
      imagePullSecrets:
        - name: wudimanong-ecr
      containers:
        - name: __APP_NAME__
          image: __IMAGE__
          resources:
            requests:
              memory: "1000M"
            limits:
              memory: "1000M"
          volumeMounts:
            - name: time-zone
              mountPath: /etc/localtime
            - name: java-logs
              mountPath: /opt/logs
          ports:
            - containerPort: __PORT__
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: __PROFILE__
            - name: JAVA_OPTS
              value: -Xms1G -Xmx1G -Dapp.home=/opt/
      volumes:
        - name: time-zone
          hostPath:
            path: /etc/localtime
        - name: java-logs
          hostPath:
            path: /data/app/deployment/logs