name: spring-reactive-kotlin-co

on:
  push:
    paths:
      - "kotlin-co/**"
    branches: [ master ]
  pull_request:
    paths:
      - "kotlin-co/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: Start up databases via Docker Compose 
      run: |
        docker-compose up -d mongodb
        sleep 5
        docker ps -a  
    - name: Build with Maven
      run: |
        cd kotlin-co
        mvn -B package --file pom.xml
