spring:
  application:
    name: consumer-user

server:
  port: 8200

eureka:
  instance:
    prefer-ip-address: true # use ip address when register service
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/