name: Docker Image CI - springEmployeeSystem

on:
  push:
    branches: [ "dev-020-fix-vue-docker-build" ]
  pull_request:
    branches: [ "dev-020-fix-vue-docker-build" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose -f springEmployeeSystem/docker-compose.yml build --tag employee_system-image-$(date +%s)
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Show Docker image
      run: docker images
    - name: Push the Docker image
      run: docker push  employee_system-image-$(date +%s)
