name: Docker Compose Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker images
        run: docker-compose --project-name springShoppingCart -f ShoppingCart/docker-compose.yml build

      - name: Push Docker images
        run: docker-compose -f ShoppingCart/docker-compose.yml push
